name: ci-cd

on:
  push:
    branches:
      - main # main 브랜치에서 push 이벤트가 일어났을 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 소스를 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 의존성 설치
      - name: Install dependencies
        run: npm install

      # 빌드 실행
      - name: Build the project
        run: npm run build

      # 현재 디렉토리 확인 (디버깅용)
      - name: pwd in build
        run: pwd

      # S3에 배포
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          BUILD_DIR=/home/runner/work/DFDD/DFDD/build

          echo "▶ Uploading HTML files with no-cache"
          find $BUILD_DIR -name "*.html" | while read filepath; do
            relative_path="${filepath#$BUILD_DIR/}"
            aws s3 cp "$filepath" "s3://df-react-dd/$relative_path" \
              --region ap-northeast-2 \
              --cache-control "no-cache"
          done

          echo "▶ Uploading other files with long-term cache"
          aws s3 cp \
            $BUILD_DIR \
            s3://df-react-dd/ \
            --recursive \
            --exclude "*.html" \
            --region ap-northeast-2 \
            --cache-control "max-age=31536000, immutable"
